### ISSUE TITLE
Requirement for Python3

### ISSUE THREAD

**Issue by yenWu** [mlouielu/twstock#1]
Great work, guy!

Just a little reminder. It should only work in Python3.
```
File "twstock/stock.py", line 30
   def fetch(self, year: int, month: int, sid: str, retry=5):
```
Maybe you could put this requirement into `README`. : )

**Comment by mlouielu** [comment]
Yep, twstock were using mypy and type annotation, so it will need to require py3, I'll add on at Monday. Thanks for your report!

**Comment by mlouielu** [comment]
Solve by 25c3f30b89c
