### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by mayboy1234567** [mlouielu/twstock#112]
twstock.realtime.get一旦使用就會出現SSL認證錯誤，原本都是正常的，電腦都沒有變更過，也有試過另外一台電腦，狀況一樣，一台untuntu, 一台win 11.
只要twstock.realtime.get('2454')就能複製問題。

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
...
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mis.twse.com.tw', port=443): Max retries exceeded with url: /stock/index.jsp (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

twstock -U更新也會失敗：
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='isin.twse.com.tw', port=8443): Max retries exceeded with url: /isin/C_public.jsp?strMode=2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x753a6aa1c2b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by AKKOU** [comment]
+1 這邊也遇到一樣的問題，本來都運行的好好的，今天突然爆掉。
![image](https://github.com/mlouielu/twstock/assets/74853569/8de29054-1535-4a30-ab4d-0db32684ff4e)

**Comment by boyu8266** [comment]
Code:
```Python
from twstock.realtime import get

data: dict = get(stock)
```

Error:
```Python
HTTPSConnectionPool(host='mis.twse.com.tw', port=443): Max retries exceeded with url: /stock/index.jsp (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))
```

**Comment by chsiang426** [comment]
請問你們有解決嗎
