### ISSUE TITLE
我第一次要執行，發現股票清單比較舊，執行twstock -U卻始終timeout 

### ISSUE THREAD

**Issue by DanielChung520** [mlouielu/twstock#114]
。  File "/Users/Daniel/PycharmProjects/StockAuction/.venv/lib/python3.12/site-packages/requests/api.py", line 59, in request     return session.request(method=method, url=url, **kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/Daniel/PycharmProjects/StockAuction/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request     resp = self.send(prep, **send_kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/Daniel/PycharmProjects/StockAuction/.venv/lib/python3.12/site-packages/requests/sessions.py", line 725, in send     history = [resp for resp in gen]               ^^^^^^^^^^^^^^^^^^^^^^   File "/Users/Daniel/PycharmProjects/StockAuction/.venv/lib/python3.12/site-packages/requests/sessions.py", line 266, in resolve_redirects     resp = self.send(            ^^^^^^^^^^   File "/Users/Daniel/PycharmProjects/StockAuction/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send     r = adapter.send(request, **kwargs)         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/Daniel/PycharmProjects/StockAuction/.venv/lib/python3.12/site-packages/requests/adapters.py", line 501, in send     raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

**Comment by mlouielu** [comment]
Close by #117. Please try again `twstock -U`.
