### ISSUE TITLE
無法取得上櫃資料

### ISSUE THREAD

**Issue by colinchu1974** [mlouielu/twstock#130]
前陣子都可以正常運作
這幾天不知道為何無法取得上櫃資料,只能取得上市資料
# 更新
twstock.__update_codes()   
 
# JSON存放的目錄與檔案
json_file_path = os.path.join('db', 'TwRealTimeStocks.json')

print(json_file_path)

#讀取股票代碼
stock_codes = read_stock_codes_from_json(json_file_path)

#初始化條件
year=2024 #年份
month=6   #月份

for stock_code in stock_codes:
    check_index=0
    stock = twstock.Stock(stock_code)
    print('股號:',stock_code,twstock.codes[stock_code].name)    
    if len(stock.high)==0: 
        print('stock.high is empty')
        continue #如果stock.high is empty,跳過這次迭代, 下一個繼續執行   
    time.sleep(2) #每2秒更新一次,用1秒會被ban
    
    stock.fetch_from(year, month) # 下載 2024 年 5 月以後的數據
    #去除None的資料
    fhigh=list(filter(None,stock.high))
    flow=list(filter(None,stock.low))
    fclose=list(filter(None,stock.close))
    fopen=list(filter(None,stock.open))
    #print(stock.capacity)
    fcapacity=list(filter(None,stock.capacity))  
    #print(fcapacity)    
    
     #計算趨勢,頭頭高,底底高
    max_points,min_points=Get_Local_max_min(stock.sid,fopen,fhigh,flow,fclose)
     
    prev_cap = fcapacity[-1]/1000 #前一天量
    pre_high=fhigh[-1]#前一天最高點
    pre_close=fclose[-1]#前一天收盤價
    

    #print(twstock.codes[stock_code].name)

    Real_time_data = twstock.realtime.get(stock_code)

    #print(Real_time_data)
    #price=Real_time_data['realtime']['latest_trade_price']
    if Real_time_data['success']:
        price_str = Real_time_data['realtime']['latest_trade_price']#當日即時股價
        try:
            price = float(price_str)   #當日即時股價
           # print('當日即時股價:',price,'前一天最高價:',pre_high,'前一天收盤價:', pre_close)
            
        except ValueError:
            print("Conversion failed, invalid string format.")
            #print('price_str:',price_str)
            price_str=Real_time_data['realtime']['best_bid_price'][0]#當日即時股價
           # print('best_bid_price:',price_str)
            if  price_str != '-':
                price = float(price_str)
                print('best_bid_price:',Real_time_data['realtime']['best_bid_price'][0])
                
            else:
                price_str=Real_time_data['realtime']['best_ask_price'][0]#當日即時股價
                price = float(price_str)
                print('best_ask_price:',Real_time_data['realtime']['best_ask_price'][0])
                
            #print('當日即時股價:',price,'前一天最高價:',pre_high)
                
           
 
    cap_str =  Real_time_data['realtime']['accumulate_trade_volume']#當日即時量
    try:
        stock_cap = float(cap_str)   #當日即時股價
        #print('當日即時量:',stock_cap,'前一日收盤量:',stock.capacity[-1]/1000)
    except ValueError:
        print("Conversion volume failed, invalid string format.")
 
  
   
------------------------------
股號: 3709 鑫聯大投控
stock.high is empty

股號: 3710 連展投控
stock.high is empty

股號: 3712 永崴投控
0線上揚
ma5_d: -0.5 ma10_d: -2.5999999999999943 ma20_d: -4.099999999999994 ma60_d: -4.199999999999996
K: 21.013415102401943 D: 21.4465606483831

股號: 3714 富采
3線上揚
ma5_d: 1.3999999999999986 ma10_d: -0.10000000000000142 ma20_d: 1.3500000000000014 ma60_d: 8.549999999999997
K: 51.7525743688751 D: 50.220837846491534

**Comment by PolunLin** [comment]
```
class TPEXFetcher(BaseFetcher):
    REPORT_URL = urllib.parse.urljoin(
        TPEX_BASE_URL, "www/zh-tw/afterTrading/tradingStock"
    )

    def __init__(self):
        pass

    def fetch(self, year: int, month: int, sid: str, retry: int = 5):
        
        params = {"date": "%d/%02d/%s" % (year, month,'01'), "code": sid}
        for retry_i in range(retry):

            r = requests.get(self.REPORT_URL, params=params, proxies=get_proxies())
            try:
                data = r.json()['tables'][0]

            except JSONDecodeError:
                continue
            else:
                break
        else:
            # Fail in all retries
            data = {"data": []}

        # data["data"] = []
        if data["data"]:
            data["data"] = self.purify(data)
        return data

    def _convert_date(self, date):
        """Convert '106/05/01' to '2017/05/01'"""
        return "/".join([str(int(date.split("/")[0]) + 1911)] + date.split("/")[1:])

    def _make_datatuple(self, data):

        data[0] = datetime.datetime.strptime(
            self._convert_date(data[0].replace("＊", "")), "%Y/%m/%d"
        )
        data[1] = int(data[1].replace(",", "")) * 1000
        data[2] = int(data[2].replace(",", "")) * 1000
        data[3] = None if data[3] == "--" else float(data[3].replace(",", ""))
        data[4] = None if data[4] == "--" else float(data[4].replace(",", ""))
        data[5] = None if data[5] == "--" else float(data[5].replace(",", ""))
        data[6] = None if data[6] == "--" else float(data[6].replace(",", ""))
        data[7] = float(data[7].replace(",", ""))
        data[8] = int(data[8].replace(",", ""))
        return DATATUPLE(*data)

    def purify(self, original_data):
        return [self._make_datatuple(d) for d in  original_data['data']]
```


<img width="1183" alt="image" src="https://github.com/user-attachments/assets/c7fa097b-8b7d-4076-9567-66598bc29bc8">

**Comment by colinchu1974** [comment]
謝謝,問題解決了
