### ISSUE TITLE
My IP seems be blocked by www.twse.com.tw after I test my code....

### ISSUE THREAD

**Issue by hushanhsiang** [mlouielu/twstock#25]
After I tried to test my program with your twstock module several times, I got below Error message and 
also, cannot access ww.twse.com by web-browser which is terrible to me.
 At the same time. I used my mobile phone to access www.twse.com.tw is OK.
So, I think my IP is already blocked.

Is there any network policy of TWSE? 
Please Help!!!

>>> stock = twstock.Stock('2330')
............
............
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**Comment by mlouielu** [comment]
It will ban when exceed 5s/3query
