### ISSUE TITLE
2017 12/18 大樹(6469) Error

### ISSUE THREAD

**Issue by JonsonChang** [mlouielu/twstock#27]
2017 12/18 大樹(6469) ，當天無交易量，證交所的資料為 '--'
程式會出現 Error。

希望能自動拿前一天的收盤價取代表示。

**Comment by ianlini** [comment]
現在的解法似乎是直接拿掉那天。
另外，我覺得有點奇怪，我看了幾個出現 '--' 的，他們那天其實有成交量，不知道是不是盤後成交？
如果是的話，那天其實還是有資訊，不應該拿掉。
我個人認為要怎麼補是要另外設定的事，我更傾向於在我自己的程式做到這件事。如果能把那四個出現 '--' 的欄位填 `None` 之類的，我覺得更好。

**Comment by mlouielu** [comment]
As we discuss in #33 , `'--'` data will convert to `None`. This bug fix @ianlini will take on it. In the future, this may be add a option to let user to choose to skip or not (convert to None).
