### ISSUE TITLE
fetch_from (y, m) ERROR : simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ShawnLee68** [mlouielu/twstock#30]
我實在對證交所公開歷史價格的網站很感冒
每次訪問伺服器只能訪問某一個月
如果我一次要10年的資料，我是不是要訪問120次?
如果要100檔股票10年，是不是要1200次?
訪問頻率是4秒一次，高了會被鎖
然後，我需要690多家公司從2000年到今天的歷史資料，算了一下要7天
現在用這個庫，fetch_from是不能用的，除了這個報錯外，你們的數據有時後會含有'--'的資料，也就是當日沒開盤，這個沒辦法轉float

這個我在自己的爬蟲程式就遇到過了，麻煩發表一個開源的庫能不能專業一點?

**Comment by mlouielu** [comment]
Hi, @ShawnLee68 你好。

這個模組是透過證交所的伺服器取得資料的，所以對於證交所的限制，你必須要自己去繞過去。

關於含有 '--' 資料的問題，已經在 #35 以 None 來處理。

發表開源專案的目的，就在於如果各位有需要，歡迎善意的來討論，或是提交 PR 讓這個模組變得更好。

工程師遇到問題，應該是要用工程的方式解決，而不是恣意批評。對於開源專案，我也不用承擔你的批評。謝謝。
