### ISSUE TITLE
How can I convert each item in stock.price list to float type variable?

### ISSUE THREAD

**Issue by snowuyl** [mlouielu/twstock#42]
Hi mlouielu,

     I would like to convert each item in stock.price list to float type variable. Could you kindly to tell me how to do it?
stock = Stock('2330')
>>> stock.price
[203.5, 203.0, 205.0, 205.0, 205.5, 207.0, 207.0, 203.0, 207.0, 209.0, 209.0, 212.0, 210.5, 211.5, 213.0, 212.0, 207.5, 208.0, 207.0, 208.0, 211.5, 213.0, 216.5, 215.5, 218.0, 217.0, 215.0, 211.5, 208.5, 210.0, 208.5]

snowuyl

**Comment by snowuyl** [comment]
I have fixed issue by getting close price as following function.
def get_year_price_list(stk, year):
    year_price_list = []
    for month in range(1, 12):
        print(year + "/" + month)
        month_price_data = stk.fetch(year, month)
        for day in month_price_data:
            print(type(day.close))
            print(day.close)
            year_price_list.append(day.close)
    print(year_price_list)        
    return year_price_list

**Comment by mlouielu** [comment]
Yes, you can use for loop to get the value in the list
