### ISSUE TITLE
Quickstart: 認識 codes 的上櫃股票部份有誤

### ISSUE THREAD

**Issue by kymindream72** [mlouielu/twstock#50]
"認識Codes " 裡面的簡介有些問題

上櫃公司那邊

>>> import twstock
>>> '2330' in twstock.twse
True
>>> '6223' in twstock.twse
False
=========應該改為=======
>>> import twstock
>>> '2330' in twstock.tpex
True
>>> '6223' in twstock.tpex
False

**Comment by mlouielu** [comment]
2330 跟 6223 都是上市公司 twse 是上市公司, tpes 是上櫃公司的。

**Comment by mlouielu** [comment]
原來是在 quickstart 那邊，reopen 這個 issue。

你要嘗試修正看看嗎？

**Comment by mlouielu** [comment]
Fixed by #62
