### ISSUE TITLE
停牌交易即時查詢會報錯

### ISSUE THREAD

**Issue by jim800121** [mlouielu/twstock#59]
in realtime.py
line 26, in _format_stock_info
    result['timestamp'] = int(data['tlong']) / 1000
KeyError: 'tlong'

**Comment by mlouielu** [comment]
可以提供一份最小可行的程式碼嗎？

thanks

**Comment by mlouielu** [comment]
應該說，你查詢的是哪個代號呢？

**Comment by mlouielu** [comment]
我從這邊沒有看到目前有異常的股票
http://www.twse.com.tw/zh/page/announcement/BFZFZU_U.html

**Comment by jim800121** [comment]
Thanks!
我昨天是盤中查2231為升的時候有出錯 但是收盤就好了
如果有再碰到我再把更詳細的資訊放上來

**Comment by mlouielu** [comment]
好的，那我先把這個 issue 關掉了, thanks.
