### ISSUE TITLE
stockcode 00757/00762讀不到

### ISSUE THREAD

**Issue by hunixhsu** [mlouielu/twstock#60]
Python 3.4/3.6都一樣的錯誤
Python 3.4.9 (default, Feb  5 2019, 14:36:09)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import twstock
>>> print(twstock.codes['00757'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '00757'
>>> print(twstock.codes['00762'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '00762'

**Comment by mlouielu** [comment]
Please refer to afac4dac, to use cli (`$ twstock -U`) or `twstock.__update_codes()` to update codes to latest version
