### ISSUE TITLE
Can't fetch historical data before 2010

### ISSUE THREAD

**Issue by hvgmbdmg** [mlouielu/twstock#72]
Here is a simple example :
```
stock = Stock('2330')
stock.fetch(2008, 4)
for index in range(len(stock.data)):
    print(stock.data[index])

print(len(stock.data))
```

The result shows that stock.data is empty.
By the way, if fetch date after 2010, it will be workable.
Does anyone meet the same problem?

**Comment by mlouielu** [comment]
This is because TWSE has the limit that you cannot query before 20100104:

```
{"stat":"查詢日期小於99年1月4日，請重新查詢!"}
```
