### ISSUE TITLE
獲取股票代號6699返回false

### ISSUE THREAD

**Issue by asd3427** [mlouielu/twstock#74]
{'msgArray': [], 'userDelay': 5000, 'rtmessage': 'Empty Query.', 'referer': '', 'queryTime': {'sysTime': '16:39:33', 'sessionLatestTime': -1, 'sysDate': '20190710', 'sessionFromTime': -1, 'stockInfoItem': 2657, 'showChart': False, 'sessionStr': 'UserSession', 'stockInfo': 556329}, 'rtcode': '5001', 'success': False}

**Comment by kevin811103** [comment]
台灣沒有6699 這檔股票吧

**Comment by asd3427** [comment]
有噢
http://pchome.megatime.com.tw/stock/sid6669.html

**Comment by asd3427** [comment]
抱歉 是我抓錯了股票代碼
