### ISSUE TITLE
請問可以查詢ETF嗎

### ISSUE THREAD

**Issue by dennis8989** [mlouielu/twstock#91]
請問可以查詢ETF嗎
我搜尋00881（國泰台灣5G+）
沒有反應

**Comment by mlouielu** [comment]
Please update your codes

```
$ python -m twstock -U
Start to update codes
Done!
```

**Comment by dennis8989** [comment]
不好意思再請問一下
可以查詢大盤指數嗎

**Comment by momolly1024** [comment]
hi  
now code 
`>>> twstock.realtime.get('00881')
`
or else ETF (like 00878)

get 

`
{'msgArray': [],
 'queryTime': {'sessionFromTime': -1,
  'sessionLatestTime': -1,
  'sessionStr': 'UserSession',
  'showChart': False,
  'stockInfo': 223564,
  'stockInfoItem': 2203,
  'sysDate': '20210518',
  'sysTime': '20:04:57'},
 'referer': '',
 'rtcode': '5001',
 'rtmessage': 'Empty Query.',
 'success': False,
 'userDelay': 5000}
`


but the other stock(like 2330) is Success XD

**Comment by mlouielu** [comment]
> hi
> now code
> `>>> twstock.realtime.get('00881') `
> or else ETF (like 00878)
> 
> get
> 
> `{'msgArray': [], 'queryTime': {'sessionFromTime': -1, 'sessionLatestTime': -1, 'sessionStr': 'UserSession', 'showChart': False, 'stockInfo': 223564, 'stockInfoItem': 2203, 'sysDate': '20210518', 'sysTime': '20:04:57'}, 'referer': '', 'rtcode': '5001', 'rtmessage': 'Empty Query.', 'success': False, 'userDelay': 5000}`
> 
> but the other stock(like 2330) is Success XD

Please update your codes first.


```
>>> import twstock
>>> twstock.realtime.get('00878')
{'timestamp': 1621319400.0, 'info': {'code': '00878', 'channel': '00878.tw', 'name': '國泰永續高股息', 'fullname': '國泰台灣高股息傘型證券投資信託基金之台灣ESG永續高股息ETF證券投資信託基金', 'time': '2021-05-18 14:30:00'}, 'realtime': {'latest_trade_price': '17.9000', 'trade_volume': '283', 'accumulate_trade_volume': '15047', 'best_bid_price': ['17.8900', '17.8800', '17.8700', '17.8600', '17.8500'], 'best_bid_volume': ['491', '143', '574', '215', '668'], 'best_ask_price': ['17.9000', '17.9100', '17.9200', '17.9300', '17.9400'], 'best_ask_volume': ['38', '28', '73', '132', '220'], 'open': '17.4500', 'high': '17.9000', 'low': '17.4000'}, 'success': True}
>>> twstock.realtime.get('00881')
{'timestamp': 1621319400.0, 'info': {'code': '00881', 'channel': '00881.tw', 'name': '國泰台灣5G+', 'fullname': '國泰台灣5G PLUS ETF證券投資信託基金', 'time': '2021-05-18 14:30:00'}, 'realtime': {'latest_trade_price': '16.9000', 'trade_volume': '1359', 'accumulate_trade_volume': '50975', 'best_bid_price': ['16.9000', '16.8900', '16.8800', '16.8700', '16.8600'], 'best_bid_volume': ['522', '23', '298', '750', '455'], 'best_ask_price': ['16.9100', '16.9200', '16.9300', '16.9400', '16.9500'], 'best_ask_volume': ['518', '204', '341', '158', '224'], 'open': '16.3000', 'high': '16.9100', 'low': '16.2600'}, 'success': True}
>>> import datetime
>>> datetime.datetime.now()
datetime.datetime(2021, 5, 18, 20, 12, 10, 187091)
```
