### ISSUE TITLE
查詢代號：1795時程式會出現錯誤

### ISSUE THREAD

**Issue by JTQueena** [mlouielu/twstock#93]
目前發現查到這檔會產生以下錯誤
IndexError: list index out of range

其他則沒有問題，不曉得有沒有方法可以排除，謝謝

**Comment by mlouielu** [comment]
Please provide minimum workable program, what I test here:

```
➜  twstock git:(master) ✗ python -m twstock -b 1795
四大買賣點判斷 Best Four Point
------------------------------
1795: Buy   量大收紅
➜  twstock git:(master) ✗ python -m twstock -s 1795
-------------- 1795 ---------------- 
high :  88.5  86.2  85.8  84.4  85.7
low  :  85.2  84.3  84.1  82.1  82.1
price:  85.3  85.6  84.9  82.6  84.9
```

I would suggest you to do `python -m twstock -U` to update codes, then try again.

**Comment by JTQueena** [comment]
謝謝回覆
我是使用這個程式
https://github.com/JTQueena/Stock/blob/master/MAtoTXT.py
當第3行的列表運行到1795時即會產生錯誤訊息, 程式中止
如果列表只有1795時就會直接產生錯誤

**Comment by mlouielu** [comment]
> 謝謝回覆
> 我是使用這個程式
> https://github.com/JTQueena/Stock/blob/master/MAtoTXT.py
> 當第3行的列表運行到1795時即會產生錯誤訊息, 程式中止
> 如果列表只有1795時就會直接產生錯誤

I assume you didn't update codes.

Do you update your codes?

```
$ twstock -U

or

$ python
>>> import twstock
>>> twstock.__update_codes()
```

Please do it once, and try again your code.

Thanks.

**Comment by JTQueena** [comment]
更新代碼後已經能運作，非常感謝您的協助·。
It works after updating the code, thank you very much for your assistance.

**Comment by mlouielu** [comment]
> 更新代碼後已經能運作，非常感謝您的協助·。
> It works after updating the code, thank you very much for your assistance.

No problem, have fun!

**Comment by mlouielu** [comment]
> [@mlouielu](https://github.com/mlouielu) Hi, I have the same issue now. Although I've already update `twstock` codes, but still get : `IndexError: list index out of range`
> 
> My goal is to run all codes to check if it's best four points. Here's my code.
> 
> import twstock
> import tqdm
> 
> # update
> twstock.__update_codes()
> 
> with open('opt', 'w') as file:
> 	data = [key for key, value in twstock.codes.items()]
> 	for k in tqdm.tqdm(data):
> 		print(k)
> 		stock = twstock.Stock(k)
> 		bfp = twstock.BestFourPoint(stock)
> 		file.write(f'----------\nkey: {k}\n四大買點: {bfp.best_four_point_to_buy()}\n四大賣點: {bfp.best_four_point_to_sell()}\n綜合: {bfp.best_four_point()}')
> std output:
> 
> ```
> 70340U
>   0%|                                                                   | 0/45730 [00:01<?, ?it/s]
> Traceback (most recent call last):
>   File "/Users/hanasay/Documents/TWStockTracker/test.py", line 14, in <module>
>     file.write(f'----------\nkey: {k}\n四大買點: {bfp.best_four_point_to_buy()}\n四大賣點: {bfp.best_four_point_to_sell()}\n綜合: {bfp.best_four_point()}')
>                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/hanasay/miniconda3/envs/test/lib/python3.11/site-packages/twstock/analytics.py", line 122, in best_four_point_to_buy
>     self.best_buy_1(),
>     ^^^^^^^^^^^^^^^^^
>   File "/Users/hanasay/miniconda3/envs/test/lib/python3.11/site-packages/twstock/analytics.py", line 75, in best_buy_1
>     self.stock.capacity[-1] > self.stock.capacity[-2]
>     ~~~~~~~~~~~~~~~~~~~^^^^
> IndexError: list index out of range
> ```



Related to #131

**Comment by hanasay** [comment]
After I reinstall twstock package `from source`
I still facing the same problem, can you help me to solve this?

The error message:

```bash
$ twstock -b 70340U

Traceback (most recent call last):
  File "/Users/hanasay/miniconda3/envs/test/bin/twstock", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/hanasay/miniconda3/envs/test/lib/python3.11/site-packages/twstock/cli/__init__.py", line 21, in run
    best_four_point.run(args.bfp)
  File "/Users/hanasay/miniconda3/envs/test/lib/python3.11/site-packages/twstock/cli/best_four_point.py", line 18, in run
    bfp = bfp.best_four_point()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hanasay/miniconda3/envs/test/lib/python3.11/site-packages/twstock/analytics.py", line 152, in best_four_point
    buy = self.best_four_point_to_buy()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hanasay/miniconda3/envs/test/lib/python3.11/site-packages/twstock/analytics.py", line 122, in best_four_point_to_buy
    self.best_buy_1(),
    ^^^^^^^^^^^^^^^^^
  File "/Users/hanasay/miniconda3/envs/test/lib/python3.11/site-packages/twstock/analytics.py", line 75, in best_buy_1
    self.stock.capacity[-1] > self.stock.capacity[-2]
    ~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
四大買賣點判斷 Best Four Point
------------------------------
```
