### ISSUE TITLE
60日線 跟 240日線 無法顯示

### ISSUE THREAD

**Issue by liharryboy** [mlouielu/twstock#96]
stock.moving_average(stock.price, 5) ~  stock.moving_average(stock.price, 30) 
沒有問題，都能正常顯示。

但想要抓月線(60) 跟年線(240) 會出現空資料。
想請問有解決辦法嗎?

感謝作者提供這麼好的套件!

**Comment by mlouielu** [comment]
預設只會抓取前 31 日之資料，其他部份需要使用 `fetch*()` function 取得:

ref: https://twstock.readthedocs.io/zh_TW/latest/quickstart.html#id3


```
>>> stock.fetch(2015, 7)  # 獲取 2015 年 7 月之股票資料
>>> stock.fetch(2010, 5)  # 獲取 2010 年 5 月之股票資料
>>> stock.fetch_31()      # 獲取近 31 日開盤之股票資料
>>> stock.fetch_from(2000, 10)  # 獲取 2000 年 10 月至今日之股票資料
```

**Comment by liharryboy** [comment]
謝謝回覆! 已解決
