### ISSUE TITLE
Unittest 總是遇到 AssertError 

### ISSUE THREAD

**Issue by LorneWu** [mlouielu/twstock#97]
# Unittest 總是遇到 AssertError

![image-20211011154753854](https://user-images.githubusercontent.com/10405270/136753305-1fcb07e7-7ff3-4226-a70c-ca65d15ade10.png)

我看起來是 `'http://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch={stock_id}&_={time}'` api 格式有變

原先是 `dict_keys(['msgArray', 'userDelay', 'rtmessage', 'referer', 'queryTime', 'rtcode'])`

後來新增了一些欄位 `dict_keys(['msgArray', 'referer', 'userDelay', 'rtcode', 'queryTime', 'rtmessage', 'exKey', 'cachedAlive'])`

所以導致 

```python
AssertionError: Element counts were not equal:
First has 1, Second has 0:  'exKey'
First has 1, Second has 0:  'cachedAlive'
```

Reference link :

https://travis-ci.org/github/mlouielu/twstock/jobs/764044874
https://travis-ci.org/github/mlouielu/twstock/jobs/772273350

**Comment by mlouielu** [comment]
Fixed in #125, thanks.
